/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparencia;

import dto.Aluno;
import dto.Bloco;
import dto.Mestrando;
import dto.Reserva;
import dto.Sala;
import dto.Servidor;
import dto.TiposSala;
import dto.Usuario;
import java.util.ArrayList;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ericapetersc
 */
public class JanelaFazerReserva extends javax.swing.JFrame {

    private Usuario u;
    private String periodo;
    private String data;
    private String codigo;
    private Bloco b;

    /**
     * Creates new form JanelaFazerReserva
     */
    public JanelaFazerReserva() {
        initComponents();
        Op2.setEnabledAt(1, false);
        Usuario[] usuarios = new Usuario[negocio.NegocioFacade.resgatarUsuarios().length];
        usuarios = negocio.NegocioFacade.resgatarUsuarios();
        for (int i = usuarios.length - 1; i >= 0; i--) {
            boxUsuario.addItem(usuarios[i].getCPF() + " - " + usuarios[i].getNome());
        }
        AutoCompleteDecorator.decorate(boxUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        Op2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boxUsuario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        boxPeriodo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dataCampo = new javax.swing.JFormattedTextField();
        Avancar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        boxBloco = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxSala = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Voltar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        codigoCampo = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Selecione as opções:");

        jLabel1.setText("Usuário:");

        jLabel2.setText("Período:");

        boxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));

        jLabel3.setText("Data:");

        try {
            dataCampo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Avancar.setText("AVANÇAR");
        Avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvancarActionPerformed(evt);
            }
        });

        Voltar.setText("CANCELAR");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jLabel8.setText("Bloco:");

        boxBloco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "F", "G", "H", "K" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Avancar)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(boxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxPeriodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataCampo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(boxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Avancar)
                    .addComponent(Voltar))
                .addGap(40, 40, 40))
        );

        Op2.addTab("Opções", jPanel1);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Escolha a sala:");

        jLabel7.setText("Salas disponíveis:");

        jButton2.setText("RESERVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Voltar1.setText("CANCELAR");
        Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Código da reserva:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(codigoCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(boxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(Voltar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(boxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(codigoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Voltar1))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        Op2.addTab("Sala", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Op2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Op2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvancarActionPerformed
        //Remove o nome do CPF no valor selecionado do comboBox
        String valorCombo = boxUsuario.getSelectedItem().toString();
        int pos = valorCombo.indexOf(" - ");
        String substring = valorCombo.substring(0, pos);

        this.u = negocio.NegocioFacade.consultarUsuario(substring);
        this.periodo = "Manha";
        switch (boxPeriodo.getSelectedIndex()) {
            case 0:
                this.periodo = "Manha";
                break;
            case 1:
                this.periodo = "Tarde";
                break;
            case 2:
                this.periodo = "Noite";
                break;
        }

        this.data = dataCampo.getText();

        this.b = negocio.NegocioFacade.resgatarBlocos()[0];

        switch (boxBloco.getSelectedIndex()) {
            case 0:
                this.b = negocio.NegocioFacade.resgatarBlocos()[0];
                break;
            case 1:
                this.b = negocio.NegocioFacade.resgatarBlocos()[1];
                break;
            case 2:
                this.b = negocio.NegocioFacade.resgatarBlocos()[2];
                break;
            case 3:
                this.b = negocio.NegocioFacade.resgatarBlocos()[3];
                break;
            case 4:
                this.b = negocio.NegocioFacade.resgatarBlocos()[4];
                break;
        }

        Op2.setSelectedIndex(1);
        Op2.setEnabledAt(1, true);

        Sala[] salas = negocio.NegocioFacade.resgatarSalas(b);

        Reserva[] reservas = negocio.NegocioFacade.regatarReservas();

        ArrayList<Sala> salasReservadas = new ArrayList<>();

        for (Reserva r : reservas) {
            if (r.getData().equals(data) && r.getPeriodo().equals(periodo) && r.getBloco().equals(b)) {
                salasReservadas.add(r.getSala());
            }
        }

        /*Preenchendo o combo de sala. Não estamos printando o tipo da sala
        Pois depois nao conseguimos pegar qual o numero da sala*/
        if (!(u instanceof Servidor) && !(u instanceof Mestrando)) {
            for (Sala s : salas) {
                if (!(salasReservadas.contains(s)) && !(s.getTipo().equals(TiposSala.LABORATORIO))) {
                    boxSala.addItem(String.valueOf(s.getNumero()) + " - " + s.getTipo());
                }
            }
        } else {
            for (Sala s : salas) {
                if (!(salasReservadas.contains(s))) {
                    boxSala.addItem(String.valueOf(s.getNumero()) + " - " + s.getTipo());
                }
            }
        }

        //Verificando se já existe o codigo no banco de dados do sistema
        Random rand = new Random();
        this.codigo = String.valueOf(rand.nextInt(100));
        Reserva aux = negocio.NegocioFacade.consultarReserva(codigo);
        while (aux != null) {
            codigo = String.valueOf(rand.nextInt(100));
            aux = negocio.NegocioFacade.consultarReserva(codigo);
        }
        codigoCampo.setText(codigo);


    }//GEN-LAST:event_AvancarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switch (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cadastrar?")) {
            case 0:
                //Remove o tipo da sala do valor selecionado do comboBox
                String valorCombo = boxSala.getSelectedItem().toString();
                int pos = valorCombo.indexOf(" - ");
                String substring = valorCombo.substring(0, pos);

                Sala sala = negocio.NegocioFacade.regatarSala(b, Integer.parseInt(substring));
                Reserva r = new Reserva(u, b, sala, periodo, data, codigo);

                boolean res = negocio.NegocioFacade.fazerReserva(r);

                if (res) {
                    JOptionPane.showMessageDialog(null, "Reserva concluída");
                    this.dispose();
                    Main.menu.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Ocorreu algum erro ao cadastrar a reserva");
                }
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar1ActionPerformed
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar?")) {
            case 0:
                this.dispose();
                Main.menu.setVisible(true);
                break;
        }
    }//GEN-LAST:event_Voltar1ActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar?")) {
            case 0:
                this.dispose();
                Main.menu.setVisible(true);
                break;
        }
    }//GEN-LAST:event_VoltarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaFazerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaFazerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaFazerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaFazerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaFazerReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avancar;
    private javax.swing.JTabbedPane Op2;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton Voltar1;
    private javax.swing.JComboBox<String> boxBloco;
    private javax.swing.JComboBox<String> boxPeriodo;
    private javax.swing.JComboBox<String> boxSala;
    private javax.swing.JComboBox<String> boxUsuario;
    private javax.swing.JLabel codigoCampo;
    private javax.swing.JFormattedTextField dataCampo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
